blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.home, name='home'),
	path('photo/upload/', views.photo_upload, name='photo_upload'),
	path('blog/create/', views.blog_and_photos_upload, name='blog_create'),
	path('blog/<int:blog_id>', views.view_blog, name='view_blog'),
	path('blog/<int:blog_id>/edit', views.edit_blog, name='edit_blog'),
	path('photo/upload-multiple/', views.create_multiple_photos,name='create_multiple_photos'),
	path('follow-users/', views.follow_users, name='follow_users'),

	]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('blog.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from django.conf import settings

from PIL import Image



class Photo(models.Model):
	image = models.ImageField()
	caption = models.CharField(max_length=128, blank=True)
	uploader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	date_created = models.DateTimeField(auto_now_add=True)


	IMAGE_MAX_SIZE = (800, 800)

	def resize_image(self):
		image = Image.open(self.image)
		image.thumbnail(self.IMAGE_MAX_SIZE)
		# sauvegarde de l'image redimensionnée dans le syteme de fichiers
		# ce n'est pas methode save() du modele!
		image.save(self.image.path)

	def save(self, *args, **kwargs):
		super().save(*args, **kwargs)
		self.resize_image()



class Blog(models.Model):
	photo = models.ForeignKey(Photo, null=True, on_delete=models.SET_NULL, blank=True)
	title = models.CharField(max_length=128)
	content = models.TextField(max_length=5000)
	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
	contributors = models.ManyToManyField(settings.AUTH_USER_MODEL, through='BlogContributor', related_name='contributions')
	date_created = models.DateTimeField(auto_now_add=True)
	starred = models.BooleanField(default=False)


class BlogContributor(models.Model):
	contributor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
	contribution = models.CharField(max_length=225, blank=True)

	class Meta:
		unique_together = ('contributor', 'blog')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FotoBlog</title>
    <link rel="stylesheet" href="{% static 'app.css' %}">
</head>
<body>
    <div class="sidebar">
        <h1>FotoBlog</h1>
        <a href="{% url 'home' %}">Accueil</a>
        <a href="{% url 'blog_create' %}">Écrire un billet</a>
        {% if perms.blog.add_photo %}
           <a href="{% url 'photo_upload' %}">Télécharger une photo</a>
        {% endif %}
        <p><a href="{% url 'follow_users' %}">Suivre des utilisateurs</a></p>
        <p><a href="{% url 'create_multiple_photos' %}">Télécharger plusieurs photos</a></p>
        {% if user.is_authenticated %}
            <p>Connecté en tant que {{ request.user }}</p>
            <a href="{% url 'logout' %}">Se déconnecter</a>
        {% endif %}
    </div>

    <div class="main">
        {% block content %}{% endblock content %}
    </div>
</body>
</html>